wordpress:
  image: wordpress
  restart: always
  links:
    - wordpress_db
  ports:
    - "8080:80"

wordpress_db:
  image: mysql/mysql-server:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: sunrays
  ports: 
    - "3306:3306"

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  restart: always
  links:
    - wordpress_db
  ports:
    - "8181:80"
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: sunrayss